# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: fluentd.proto

require 'google/protobuf'

require 'google/protobuf/timestamp_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("fluentd.proto", :syntax => :proto3) do
    add_message "proto.fluentd.FluentdRecord" do
      optional :tag, :string, 1
      optional :time, :message, 2, "google.protobuf.Timestamp"
      optional :record, :bytes, 3
    end
  end
end

module Proto
  module Fluentd
    FluentdRecord = Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.fluentd.FluentdRecord").msgclass
  end
end
